source "https://rubygems.org"

gem "sinatra", "2.0.5"
gem "sinatra-contrib", "2.0.5"  # For Sinatra::Reloader
gem "erubis", "2.7.0"
gem "fishwife", "1.10.1"
gem "rjack-logback", "1.9.0"
gem "rack-protection", "2.0.5"
