source "https://rubygems.org"

gem "sinatra", "2.0.5"
gem "sinatra-contrib", "2.0.5"  # For Sinatra::Reloader
gem "erubis", "2.7.0"
gem "fishwife", "1.10.1"
gem "rjack-logback", "1.9.0"
gem "rack-protection", "2.0.5"
gem "multipart-post", "2.0.0"
gem "net-http-persistent", "3.0.1"

gem "rotp", "5.1"
gem "rqrcode", "0.10.1"
