source "https://rubygems.org"

gem "sinatra", "2.0.5"
gem "sinatra-contrib", "2.0.5"  # For Sinatra::Reloader
gem "fishwife", "1.10.1"
gem "rjack-logback", "1.9.0"
gem "json", "2.2.0"
gem "sequel", "5.19.0"

gem "bcrypt", "3.1.12"
gem "jdbc-mysql", "5.1.47"

if ENV['RELEASE_BRANCH'] == 'qa'
  gem "xlsx_streaming_reader", git: "https://github.com/hudmol/xlsx_streaming_reader.git", branch: "qa"
  gem "map_validator", git: "https://github.com/hudmol/map_validator.git", branch: "qa"
else
  gem "xlsx_streaming_reader", git: "https://github.com/hudmol/xlsx_streaming_reader.git", branch: "master"
  gem "map_validator", git: "https://github.com/hudmol/map_validator.git", branch: "master"
end
